<?xml version="1.0" encoding="utf-8"?><!DOCTYPE context [<!ELEMENT context (device | context-attribute)*><!ELEMENT context-attribute EMPTY><!ELEMENT device (channel | attribute | debug-attribute | buffer-attribute)*><!ELEMENT channel (scan-element?, attribute*)><!ELEMENT attribute EMPTY><!ELEMENT scan-element EMPTY><!ELEMENT debug-attribute EMPTY><!ELEMENT buffer-attribute EMPTY><!ATTLIST context name CDATA #REQUIRED version-major CDATA #REQUIRED version-minor CDATA #REQUIRED version-git CDATA #REQUIRED description CDATA #IMPLIED><!ATTLIST context-attribute name CDATA #REQUIRED value CDATA #REQUIRED><!ATTLIST device id CDATA #REQUIRED name CDATA #IMPLIED label CDATA #IMPLIED><!ATTLIST channel id CDATA #REQUIRED type (input|output) #REQUIRED name CDATA #IMPLIED><!ATTLIST scan-element index CDATA #REQUIRED format CDATA #REQUIRED scale CDATA #IMPLIED><!ATTLIST attribute name CDATA #REQUIRED filename CDATA #IMPLIED><!ATTLIST debug-attribute name CDATA #REQUIRED><!ATTLIST buffer-attribute name CDATA #REQUIRED>]><context name="xml" version-major="0" version-minor="23" version-git="92d6a35" description="Linux analog 4.19.0-g17f4223 #1849 SMP Tue Jul 27 13:12:14 IST 2021 aarch64" ><context-attribute name="local,kernel" value="4.19.0-g17f4223" /><context-attribute name="uri" value="local:" /><device id="iio:device0" name="ams" ><channel id="voltage6" name="vccpsintfpddr" type="input" ><attribute name="raw" filename="in_voltage6_vccpsintfpddr_raw" /><attribute name="scale" filename="in_voltage6_vccpsintfpddr_scale" /></channel><channel id="voltage14" name="vccpsio2" type="input" ><attribute name="raw" filename="in_voltage14_vccpsio2_raw" /><attribute name="scale" filename="in_voltage14_vccpsio2_scale" /></channel><channel id="voltage16" name="psmgtravtt" type="input" ><attribute name="raw" filename="in_voltage16_psmgtravtt_raw" /><attribute name="scale" filename="in_voltage16_psmgtravtt_scale" /></channel><channel id="voltage23" name="vccplintlp" type="input" ><attribute name="raw" filename="in_voltage23_vccplintlp_raw" /><attribute name="scale" filename="in_voltage23_vccplintlp_scale" /></channel><channel id="voltage0" name="vcc_pspll0" type="input" ><attribute name="raw" filename="in_voltage0_vcc_pspll0_raw" /><attribute name="scale" filename="in_voltage0_vcc_pspll0_scale" /></channel><channel id="voltage22" name="vccbram" type="input" ><attribute name="raw" filename="in_voltage22_vccbram_raw" /><attribute name="scale" filename="in_voltage22_vccbram_scale" /></channel><channel id="voltage26" name="vccams" type="input" ><attribute name="raw" filename="in_voltage26_vccams_raw" /><attribute name="scale" filename="in_voltage26_vccams_scale" /></channel><channel id="voltage8" name="vccpsintfp" type="input" ><attribute name="raw" filename="in_voltage8_vccpsintfp_raw" /><attribute name="scale" filename="in_voltage8_vccpsintfp_scale" /></channel><channel id="temp1" name="remote_temp" type="input" ><attribute name="offset" filename="in_temp1_remote_temp_offset" /><attribute name="raw" filename="in_temp1_remote_temp_raw" /><attribute name="scale" filename="in_temp1_remote_temp_scale" /></channel><channel id="voltage9" name="vccpsaux" type="input" ><attribute name="raw" filename="in_voltage9_vccpsaux_raw" /><attribute name="scale" filename="in_voltage9_vccpsaux_scale" /></channel><channel id="voltage25" name="vccplaux" type="input" ><attribute name="raw" filename="in_voltage25_vccplaux_raw" /><attribute name="scale" filename="in_voltage25_vccplaux_scale" /></channel><channel id="voltage18" name="vccint" type="input" ><attribute name="raw" filename="in_voltage18_vccint_raw" /><attribute name="scale" filename="in_voltage18_vccint_scale" /></channel><channel id="voltage15" name="psmgtravcc" type="input" ><attribute name="raw" filename="in_voltage15_psmgtravcc_raw" /><attribute name="scale" filename="in_voltage15_psmgtravcc_scale" /></channel><channel id="temp0" name="ps_temp" type="input" ><attribute name="offset" filename="in_temp0_ps_temp_offset" /><attribute name="raw" filename="in_temp0_ps_temp_raw" /><attribute name="scale" filename="in_temp0_ps_temp_scale" /></channel><channel id="voltage2" name="vccint" type="input" ><attribute name="raw" filename="in_voltage2_vccint_raw" /><attribute name="scale" filename="in_voltage2_vccint_scale" /></channel><channel id="voltage5" name="vcc_psddrpll" type="input" ><attribute name="raw" filename="in_voltage5_vcc_psddrpll_raw" /><attribute name="scale" filename="in_voltage5_vcc_psddrpll_scale" /></channel><channel id="voltage21" name="vccvrefn" type="input" ><attribute name="raw" filename="in_voltage21_vccvrefn_raw" /><attribute name="scale" filename="in_voltage21_vccvrefn_scale" /></channel><channel id="voltage7" name="vccpsintlp" type="input" ><attribute name="raw" filename="in_voltage7_vccpsintlp_raw" /><attribute name="scale" filename="in_voltage7_vccpsintlp_scale" /></channel><channel id="voltage11" name="vccpsio3" type="input" ><attribute name="raw" filename="in_voltage11_vccpsio3_raw" /><attribute name="scale" filename="in_voltage11_vccpsio3_scale" /></channel><channel id="temp2" name="pl_temp" type="input" ><attribute name="offset" filename="in_temp2_pl_temp_offset" /><attribute name="raw" filename="in_temp2_pl_temp_raw" /><attribute name="scale" filename="in_temp2_pl_temp_scale" /></channel><channel id="voltage13" name="vccpsio1" type="input" ><attribute name="raw" filename="in_voltage13_vccpsio1_raw" /><attribute name="scale" filename="in_voltage13_vccpsio1_scale" /></channel><channel id="voltage3" name="vccbram" type="input" ><attribute name="raw" filename="in_voltage3_vccbram_raw" /><attribute name="scale" filename="in_voltage3_vccbram_scale" /></channel><channel id="voltage4" name="vccaux" type="input" ><attribute name="raw" filename="in_voltage4_vccaux_raw" /><attribute name="scale" filename="in_voltage4_vccaux_scale" /></channel><channel id="voltage12" name="vccpsio0" type="input" ><attribute name="raw" filename="in_voltage12_vccpsio0_raw" /><attribute name="scale" filename="in_voltage12_vccpsio0_scale" /></channel><channel id="voltage10" name="vccpsddr" type="input" ><attribute name="raw" filename="in_voltage10_vccpsddr_raw" /><attribute name="scale" filename="in_voltage10_vccpsddr_scale" /></channel><channel id="voltage24" name="vccplintfp" type="input" ><attribute name="raw" filename="in_voltage24_vccplintfp_raw" /><attribute name="scale" filename="in_voltage24_vccplintfp_scale" /></channel><channel id="voltage1" name="vcc_psbatt" type="input" ><attribute name="raw" filename="in_voltage1_vcc_psbatt_raw" /><attribute name="scale" filename="in_voltage1_vcc_psbatt_scale" /></channel><channel id="voltage19" name="vccaux" type="input" ><attribute name="raw" filename="in_voltage19_vccaux_raw" /><attribute name="scale" filename="in_voltage19_vccaux_scale" /></channel><channel id="voltage17" name="vccams" type="input" ><attribute name="raw" filename="in_voltage17_vccams_raw" /><attribute name="scale" filename="in_voltage17_vccams_scale" /></channel><channel id="voltage20" name="vccvrefp" type="input" ><attribute name="raw" filename="in_voltage20_vccvrefp_raw" /><attribute name="scale" filename="in_voltage20_vccvrefp_scale" /></channel><attribute name="sampling_frequency" /></device><device id="iio:device1" name="hmc7044" ><channel id="altvoltage10" name="CORE_CLK_RX_ALT" type="output" ><attribute name="frequency" filename="out_altvoltage10_CORE_CLK_RX_ALT_frequency" /><attribute name="phase" filename="out_altvoltage10_CORE_CLK_RX_ALT_phase" /></channel><channel id="altvoltage0" name="CORE_CLK_RX" type="output" ><attribute name="frequency" filename="out_altvoltage0_CORE_CLK_RX_frequency" /><attribute name="phase" filename="out_altvoltage0_CORE_CLK_RX_phase" /></channel><channel id="altvoltage3" name="DEV_SYSREF" type="output" ><attribute name="frequency" filename="out_altvoltage3_DEV_SYSREF_frequency" /><attribute name="phase" filename="out_altvoltage3_DEV_SYSREF_phase" /></channel><channel id="altvoltage13" name="FPGA_SYSREF" type="output" ><attribute name="frequency" filename="out_altvoltage13_FPGA_SYSREF_frequency" /><attribute name="phase" filename="out_altvoltage13_FPGA_SYSREF_phase" /></channel><channel id="altvoltage6" name="CORE_CLK_TX" type="output" ><attribute name="frequency" filename="out_altvoltage6_CORE_CLK_TX_frequency" /><attribute name="phase" filename="out_altvoltage6_CORE_CLK_TX_phase" /></channel><channel id="altvoltage2" name="DEV_REFCLK" type="output" ><attribute name="frequency" filename="out_altvoltage2_DEV_REFCLK_frequency" /><attribute name="phase" filename="out_altvoltage2_DEV_REFCLK_phase" /></channel><channel id="altvoltage8" name="FPGA_REFCLK1" type="output" ><attribute name="frequency" filename="out_altvoltage8_FPGA_REFCLK1_frequency" /><attribute name="phase" filename="out_altvoltage8_FPGA_REFCLK1_phase" /></channel><channel id="altvoltage12" name="FPGA_REFCLK2" type="output" ><attribute name="frequency" filename="out_altvoltage12_FPGA_REFCLK2_frequency" /><attribute name="phase" filename="out_altvoltage12_FPGA_REFCLK2_phase" /></channel><attribute name="mute_request" /><attribute name="reseed_request" /><attribute name="reset_dividers_request" /><attribute name="sleep_request" /><attribute name="sync_pin_mode" /><attribute name="sync_pin_mode_available" /><attribute name="sysref_request" /><debug-attribute name="status" /><debug-attribute name="direct_reg_access" /></device><device id="iio:device2" name="axi-ad9081-rx-hpc" ><channel id="voltage0_i" type="input" ><scan-element index="0" format="le:S16/16&gt;&gt;0" /><attribute name="adc_frequency" filename="in_voltage_adc_frequency" /><attribute name="channel_6db_digital_gain_en" filename="in_voltage0_i_channel_6db_digital_gain_en" /><attribute name="channel_nco_frequency" filename="in_voltage0_i_channel_nco_frequency" /><attribute name="channel_nco_frequency_available" filename="in_voltage0_i_channel_nco_frequency_available" /><attribute name="channel_nco_phase" filename="in_voltage0_i_channel_nco_phase" /><attribute name="label" filename="in_voltage0_i_label" /><attribute name="main_6db_digital_gain_en" filename="in_voltage0_i_main_6db_digital_gain_en" /><attribute name="main_nco_frequency" filename="in_voltage0_i_main_nco_frequency" /><attribute name="main_nco_frequency_available" filename="in_voltage_main_nco_frequency_available" /><attribute name="main_nco_phase" filename="in_voltage0_i_main_nco_phase" /><attribute name="nyquist_zone" filename="in_voltage_nyquist_zone" /><attribute name="nyquist_zone_available" filename="in_voltage_nyquist_zone_available" /><attribute name="sampling_frequency" filename="in_voltage_sampling_frequency" /><attribute name="test_mode" filename="in_voltage_test_mode" /><attribute name="test_mode_available" filename="in_voltage_test_mode_available" /></channel><channel id="voltage0_q" type="input" ><scan-element index="1" format="le:S16/16&gt;&gt;0" /><attribute name="adc_frequency" filename="in_voltage_adc_frequency" /><attribute name="channel_6db_digital_gain_en" filename="in_voltage0_q_channel_6db_digital_gain_en" /><attribute name="channel_nco_frequency" filename="in_voltage0_q_channel_nco_frequency" /><attribute name="channel_nco_frequency_available" filename="in_voltage0_q_channel_nco_frequency_available" /><attribute name="channel_nco_phase" filename="in_voltage0_q_channel_nco_phase" /><attribute name="label" filename="in_voltage0_q_label" /><attribute name="main_6db_digital_gain_en" filename="in_voltage0_q_main_6db_digital_gain_en" /><attribute name="main_nco_frequency" filename="in_voltage0_q_main_nco_frequency" /><attribute name="main_nco_frequency_available" filename="in_voltage_main_nco_frequency_available" /><attribute name="main_nco_phase" filename="in_voltage0_q_main_nco_phase" /><attribute name="nyquist_zone" filename="in_voltage_nyquist_zone" /><attribute name="nyquist_zone_available" filename="in_voltage_nyquist_zone_available" /><attribute name="sampling_frequency" filename="in_voltage_sampling_frequency" /><attribute name="test_mode" filename="in_voltage_test_mode" /><attribute name="test_mode_available" filename="in_voltage_test_mode_available" /></channel><channel id="voltage1_i" type="input" ><scan-element index="2" format="le:S16/16&gt;&gt;0" /><attribute name="adc_frequency" filename="in_voltage_adc_frequency" /><attribute name="channel_6db_digital_gain_en" filename="in_voltage1_i_channel_6db_digital_gain_en" /><attribute name="channel_nco_frequency" filename="in_voltage1_i_channel_nco_frequency" /><attribute name="channel_nco_frequency_available" filename="in_voltage1_i_channel_nco_frequency_available" /><attribute name="channel_nco_phase" filename="in_voltage1_i_channel_nco_phase" /><attribute name="label" filename="in_voltage1_i_label" /><attribute name="main_6db_digital_gain_en" filename="in_voltage1_i_main_6db_digital_gain_en" /><attribute name="main_nco_frequency" filename="in_voltage1_i_main_nco_frequency" /><attribute name="main_nco_frequency_available" filename="in_voltage_main_nco_frequency_available" /><attribute name="main_nco_phase" filename="in_voltage1_i_main_nco_phase" /><attribute name="nyquist_zone" filename="in_voltage_nyquist_zone" /><attribute name="nyquist_zone_available" filename="in_voltage_nyquist_zone_available" /><attribute name="sampling_frequency" filename="in_voltage_sampling_frequency" /><attribute name="test_mode" filename="in_voltage_test_mode" /><attribute name="test_mode_available" filename="in_voltage_test_mode_available" /></channel><channel id="voltage1_q" type="input" ><scan-element index="3" format="le:S16/16&gt;&gt;0" /><attribute name="adc_frequency" filename="in_voltage_adc_frequency" /><attribute name="channel_6db_digital_gain_en" filename="in_voltage1_q_channel_6db_digital_gain_en" /><attribute name="channel_nco_frequency" filename="in_voltage1_q_channel_nco_frequency" /><attribute name="channel_nco_frequency_available" filename="in_voltage1_q_channel_nco_frequency_available" /><attribute name="channel_nco_phase" filename="in_voltage1_q_channel_nco_phase" /><attribute name="label" filename="in_voltage1_q_label" /><attribute name="main_6db_digital_gain_en" filename="in_voltage1_q_main_6db_digital_gain_en" /><attribute name="main_nco_frequency" filename="in_voltage1_q_main_nco_frequency" /><attribute name="main_nco_frequency_available" filename="in_voltage_main_nco_frequency_available" /><attribute name="main_nco_phase" filename="in_voltage1_q_main_nco_phase" /><attribute name="nyquist_zone" filename="in_voltage_nyquist_zone" /><attribute name="nyquist_zone_available" filename="in_voltage_nyquist_zone_available" /><attribute name="sampling_frequency" filename="in_voltage_sampling_frequency" /><attribute name="test_mode" filename="in_voltage_test_mode" /><attribute name="test_mode_available" filename="in_voltage_test_mode_available" /></channel><channel id="voltage2_i" type="input" ><scan-element index="4" format="le:S16/16&gt;&gt;0" /><attribute name="adc_frequency" filename="in_voltage_adc_frequency" /><attribute name="channel_6db_digital_gain_en" filename="in_voltage2_i_channel_6db_digital_gain_en" /><attribute name="channel_nco_frequency" filename="in_voltage2_i_channel_nco_frequency" /><attribute name="channel_nco_frequency_available" filename="in_voltage2_i_channel_nco_frequency_available" /><attribute name="channel_nco_phase" filename="in_voltage2_i_channel_nco_phase" /><attribute name="label" filename="in_voltage2_i_label" /><attribute name="main_6db_digital_gain_en" filename="in_voltage2_i_main_6db_digital_gain_en" /><attribute name="main_nco_frequency" filename="in_voltage2_i_main_nco_frequency" /><attribute name="main_nco_frequency_available" filename="in_voltage_main_nco_frequency_available" /><attribute name="main_nco_phase" filename="in_voltage2_i_main_nco_phase" /><attribute name="nyquist_zone" filename="in_voltage_nyquist_zone" /><attribute name="nyquist_zone_available" filename="in_voltage_nyquist_zone_available" /><attribute name="sampling_frequency" filename="in_voltage_sampling_frequency" /><attribute name="test_mode" filename="in_voltage_test_mode" /><attribute name="test_mode_available" filename="in_voltage_test_mode_available" /></channel><channel id="voltage2_q" type="input" ><scan-element index="5" format="le:S16/16&gt;&gt;0" /><attribute name="adc_frequency" filename="in_voltage_adc_frequency" /><attribute name="channel_6db_digital_gain_en" filename="in_voltage2_q_channel_6db_digital_gain_en" /><attribute name="channel_nco_frequency" filename="in_voltage2_q_channel_nco_frequency" /><attribute name="channel_nco_frequency_available" filename="in_voltage2_q_channel_nco_frequency_available" /><attribute name="channel_nco_phase" filename="in_voltage2_q_channel_nco_phase" /><attribute name="label" filename="in_voltage2_q_label" /><attribute name="main_6db_digital_gain_en" filename="in_voltage2_q_main_6db_digital_gain_en" /><attribute name="main_nco_frequency" filename="in_voltage2_q_main_nco_frequency" /><attribute name="main_nco_frequency_available" filename="in_voltage_main_nco_frequency_available" /><attribute name="main_nco_phase" filename="in_voltage2_q_main_nco_phase" /><attribute name="nyquist_zone" filename="in_voltage_nyquist_zone" /><attribute name="nyquist_zone_available" filename="in_voltage_nyquist_zone_available" /><attribute name="sampling_frequency" filename="in_voltage_sampling_frequency" /><attribute name="test_mode" filename="in_voltage_test_mode" /><attribute name="test_mode_available" filename="in_voltage_test_mode_available" /></channel><channel id="voltage3_i" type="input" ><scan-element index="6" format="le:S16/16&gt;&gt;0" /><attribute name="adc_frequency" filename="in_voltage_adc_frequency" /><attribute name="channel_6db_digital_gain_en" filename="in_voltage3_i_channel_6db_digital_gain_en" /><attribute name="channel_nco_frequency" filename="in_voltage3_i_channel_nco_frequency" /><attribute name="channel_nco_frequency_available" filename="in_voltage3_i_channel_nco_frequency_available" /><attribute name="channel_nco_phase" filename="in_voltage3_i_channel_nco_phase" /><attribute name="label" filename="in_voltage3_i_label" /><attribute name="main_6db_digital_gain_en" filename="in_voltage3_i_main_6db_digital_gain_en" /><attribute name="main_nco_frequency" filename="in_voltage3_i_main_nco_frequency" /><attribute name="main_nco_frequency_available" filename="in_voltage_main_nco_frequency_available" /><attribute name="main_nco_phase" filename="in_voltage3_i_main_nco_phase" /><attribute name="nyquist_zone" filename="in_voltage_nyquist_zone" /><attribute name="nyquist_zone_available" filename="in_voltage_nyquist_zone_available" /><attribute name="sampling_frequency" filename="in_voltage_sampling_frequency" /><attribute name="test_mode" filename="in_voltage_test_mode" /><attribute name="test_mode_available" filename="in_voltage_test_mode_available" /></channel><channel id="voltage3_q" type="input" ><scan-element index="7" format="le:S16/16&gt;&gt;0" /><attribute name="adc_frequency" filename="in_voltage_adc_frequency" /><attribute name="channel_6db_digital_gain_en" filename="in_voltage3_q_channel_6db_digital_gain_en" /><attribute name="channel_nco_frequency" filename="in_voltage3_q_channel_nco_frequency" /><attribute name="channel_nco_frequency_available" filename="in_voltage3_q_channel_nco_frequency_available" /><attribute name="channel_nco_phase" filename="in_voltage3_q_channel_nco_phase" /><attribute name="label" filename="in_voltage3_q_label" /><attribute name="main_6db_digital_gain_en" filename="in_voltage3_q_main_6db_digital_gain_en" /><attribute name="main_nco_frequency" filename="in_voltage3_q_main_nco_frequency" /><attribute name="main_nco_frequency_available" filename="in_voltage_main_nco_frequency_available" /><attribute name="main_nco_phase" filename="in_voltage3_q_main_nco_phase" /><attribute name="nyquist_zone" filename="in_voltage_nyquist_zone" /><attribute name="nyquist_zone_available" filename="in_voltage_nyquist_zone_available" /><attribute name="sampling_frequency" filename="in_voltage_sampling_frequency" /><attribute name="test_mode" filename="in_voltage_test_mode" /><attribute name="test_mode_available" filename="in_voltage_test_mode_available" /></channel><channel id="voltage3_i" type="output" ><attribute name="channel_nco_frequency" filename="out_voltage3_i_channel_nco_frequency" /><attribute name="channel_nco_frequency_available" filename="out_voltage_channel_nco_frequency_available" /><attribute name="channel_nco_gain_scale" filename="out_voltage3_i_channel_nco_gain_scale" /><attribute name="channel_nco_phase" filename="out_voltage3_i_channel_nco_phase" /><attribute name="channel_nco_test_tone_en" filename="out_voltage3_i_channel_nco_test_tone_en" /><attribute name="channel_nco_test_tone_scale" filename="out_voltage3_i_channel_nco_test_tone_scale" /><attribute name="dac_frequency" filename="out_voltage_dac_frequency" /><attribute name="en" filename="out_voltage3_i_en" /><attribute name="label" filename="out_voltage3_i_label" /><attribute name="main_ffh_frequency" filename="out_voltage_main_ffh_frequency" /><attribute name="main_ffh_index" filename="out_voltage_main_ffh_index" /><attribute name="main_ffh_mode" filename="out_voltage_main_ffh_mode" /><attribute name="main_ffh_mode_available" filename="out_voltage_main_ffh_mode_available" /><attribute name="main_nco_ffh_select" filename="out_voltage3_i_main_nco_ffh_select" /><attribute name="main_nco_frequency" filename="out_voltage3_i_main_nco_frequency" /><attribute name="main_nco_frequency_available" filename="out_voltage_main_nco_frequency_available" /><attribute name="main_nco_phase" filename="out_voltage3_i_main_nco_phase" /><attribute name="main_nco_test_tone_en" filename="out_voltage3_i_main_nco_test_tone_en" /><attribute name="main_nco_test_tone_scale" filename="out_voltage3_i_main_nco_test_tone_scale" /><attribute name="sampling_frequency" filename="out_voltage_sampling_frequency" /></channel><channel id="voltage0_i" type="output" ><attribute name="channel_nco_frequency" filename="out_voltage0_i_channel_nco_frequency" /><attribute name="channel_nco_frequency_available" filename="out_voltage_channel_nco_frequency_available" /><attribute name="channel_nco_gain_scale" filename="out_voltage0_i_channel_nco_gain_scale" /><attribute name="channel_nco_phase" filename="out_voltage0_i_channel_nco_phase" /><attribute name="channel_nco_test_tone_en" filename="out_voltage0_i_channel_nco_test_tone_en" /><attribute name="channel_nco_test_tone_scale" filename="out_voltage0_i_channel_nco_test_tone_scale" /><attribute name="dac_frequency" filename="out_voltage_dac_frequency" /><attribute name="en" filename="out_voltage0_i_en" /><attribute name="label" filename="out_voltage0_i_label" /><attribute name="main_ffh_frequency" filename="out_voltage_main_ffh_frequency" /><attribute name="main_ffh_index" filename="out_voltage_main_ffh_index" /><attribute name="main_ffh_mode" filename="out_voltage_main_ffh_mode" /><attribute name="main_ffh_mode_available" filename="out_voltage_main_ffh_mode_available" /><attribute name="main_nco_ffh_select" filename="out_voltage0_i_main_nco_ffh_select" /><attribute name="main_nco_frequency" filename="out_voltage0_i_main_nco_frequency" /><attribute name="main_nco_frequency_available" filename="out_voltage_main_nco_frequency_available" /><attribute name="main_nco_phase" filename="out_voltage0_i_main_nco_phase" /><attribute name="main_nco_test_tone_en" filename="out_voltage0_i_main_nco_test_tone_en" /><attribute name="main_nco_test_tone_scale" filename="out_voltage0_i_main_nco_test_tone_scale" /><attribute name="sampling_frequency" filename="out_voltage_sampling_frequency" /></channel><channel id="voltage1_i" type="output" ><attribute name="channel_nco_frequency" filename="out_voltage1_i_channel_nco_frequency" /><attribute name="channel_nco_frequency_available" filename="out_voltage_channel_nco_frequency_available" /><attribute name="channel_nco_gain_scale" filename="out_voltage1_i_channel_nco_gain_scale" /><attribute name="channel_nco_phase" filename="out_voltage1_i_channel_nco_phase" /><attribute name="channel_nco_test_tone_en" filename="out_voltage1_i_channel_nco_test_tone_en" /><attribute name="channel_nco_test_tone_scale" filename="out_voltage1_i_channel_nco_test_tone_scale" /><attribute name="dac_frequency" filename="out_voltage_dac_frequency" /><attribute name="en" filename="out_voltage1_i_en" /><attribute name="label" filename="out_voltage1_i_label" /><attribute name="main_ffh_frequency" filename="out_voltage_main_ffh_frequency" /><attribute name="main_ffh_index" filename="out_voltage_main_ffh_index" /><attribute name="main_ffh_mode" filename="out_voltage_main_ffh_mode" /><attribute name="main_ffh_mode_available" filename="out_voltage_main_ffh_mode_available" /><attribute name="main_nco_ffh_select" filename="out_voltage1_i_main_nco_ffh_select" /><attribute name="main_nco_frequency" filename="out_voltage1_i_main_nco_frequency" /><attribute name="main_nco_frequency_available" filename="out_voltage_main_nco_frequency_available" /><attribute name="main_nco_phase" filename="out_voltage1_i_main_nco_phase" /><attribute name="main_nco_test_tone_en" filename="out_voltage1_i_main_nco_test_tone_en" /><attribute name="main_nco_test_tone_scale" filename="out_voltage1_i_main_nco_test_tone_scale" /><attribute name="sampling_frequency" filename="out_voltage_sampling_frequency" /></channel><channel id="voltage2_i" type="output" ><attribute name="channel_nco_frequency" filename="out_voltage2_i_channel_nco_frequency" /><attribute name="channel_nco_frequency_available" filename="out_voltage_channel_nco_frequency_available" /><attribute name="channel_nco_gain_scale" filename="out_voltage2_i_channel_nco_gain_scale" /><attribute name="channel_nco_phase" filename="out_voltage2_i_channel_nco_phase" /><attribute name="channel_nco_test_tone_en" filename="out_voltage2_i_channel_nco_test_tone_en" /><attribute name="channel_nco_test_tone_scale" filename="out_voltage2_i_channel_nco_test_tone_scale" /><attribute name="dac_frequency" filename="out_voltage_dac_frequency" /><attribute name="en" filename="out_voltage2_i_en" /><attribute name="label" filename="out_voltage2_i_label" /><attribute name="main_ffh_frequency" filename="out_voltage_main_ffh_frequency" /><attribute name="main_ffh_index" filename="out_voltage_main_ffh_index" /><attribute name="main_ffh_mode" filename="out_voltage_main_ffh_mode" /><attribute name="main_ffh_mode_available" filename="out_voltage_main_ffh_mode_available" /><attribute name="main_nco_ffh_select" filename="out_voltage2_i_main_nco_ffh_select" /><attribute name="main_nco_frequency" filename="out_voltage2_i_main_nco_frequency" /><attribute name="main_nco_frequency_available" filename="out_voltage_main_nco_frequency_available" /><attribute name="main_nco_phase" filename="out_voltage2_i_main_nco_phase" /><attribute name="main_nco_test_tone_en" filename="out_voltage2_i_main_nco_test_tone_en" /><attribute name="main_nco_test_tone_scale" filename="out_voltage2_i_main_nco_test_tone_scale" /><attribute name="sampling_frequency" filename="out_voltage_sampling_frequency" /></channel><channel id="voltage3_q" type="output" ><attribute name="channel_nco_frequency" filename="out_voltage3_q_channel_nco_frequency" /><attribute name="channel_nco_frequency_available" filename="out_voltage_channel_nco_frequency_available" /><attribute name="channel_nco_gain_scale" filename="out_voltage3_q_channel_nco_gain_scale" /><attribute name="channel_nco_phase" filename="out_voltage3_q_channel_nco_phase" /><attribute name="channel_nco_test_tone_en" filename="out_voltage3_q_channel_nco_test_tone_en" /><attribute name="channel_nco_test_tone_scale" filename="out_voltage3_q_channel_nco_test_tone_scale" /><attribute name="dac_frequency" filename="out_voltage_dac_frequency" /><attribute name="en" filename="out_voltage3_q_en" /><attribute name="label" filename="out_voltage3_q_label" /><attribute name="main_ffh_frequency" filename="out_voltage_main_ffh_frequency" /><attribute name="main_ffh_index" filename="out_voltage_main_ffh_index" /><attribute name="main_ffh_mode" filename="out_voltage_main_ffh_mode" /><attribute name="main_ffh_mode_available" filename="out_voltage_main_ffh_mode_available" /><attribute name="main_nco_ffh_select" filename="out_voltage3_q_main_nco_ffh_select" /><attribute name="main_nco_frequency" filename="out_voltage3_q_main_nco_frequency" /><attribute name="main_nco_frequency_available" filename="out_voltage_main_nco_frequency_available" /><attribute name="main_nco_phase" filename="out_voltage3_q_main_nco_phase" /><attribute name="main_nco_test_tone_en" filename="out_voltage3_q_main_nco_test_tone_en" /><attribute name="main_nco_test_tone_scale" filename="out_voltage3_q_main_nco_test_tone_scale" /><attribute name="sampling_frequency" filename="out_voltage_sampling_frequency" /></channel><channel id="voltage0_q" type="output" ><attribute name="channel_nco_frequency" filename="out_voltage0_q_channel_nco_frequency" /><attribute name="channel_nco_frequency_available" filename="out_voltage_channel_nco_frequency_available" /><attribute name="channel_nco_gain_scale" filename="out_voltage0_q_channel_nco_gain_scale" /><attribute name="channel_nco_phase" filename="out_voltage0_q_channel_nco_phase" /><attribute name="channel_nco_test_tone_en" filename="out_voltage0_q_channel_nco_test_tone_en" /><attribute name="channel_nco_test_tone_scale" filename="out_voltage0_q_channel_nco_test_tone_scale" /><attribute name="dac_frequency" filename="out_voltage_dac_frequency" /><attribute name="en" filename="out_voltage0_q_en" /><attribute name="label" filename="out_voltage0_q_label" /><attribute name="main_ffh_frequency" filename="out_voltage_main_ffh_frequency" /><attribute name="main_ffh_index" filename="out_voltage_main_ffh_index" /><attribute name="main_ffh_mode" filename="out_voltage_main_ffh_mode" /><attribute name="main_ffh_mode_available" filename="out_voltage_main_ffh_mode_available" /><attribute name="main_nco_ffh_sele